#!/bin/sh

# Hook скрипт для commit message.
# Добавляет в начало Вашего commit message `JIRA_TASK_ID`, исходя из префикса текущей ветки `feature/krishaKz/KRIA-562-add-linter`
# Пример: `Добавил SwiftLint`` -> `KRIA-562 Добавил SwiftLint``

if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master develop test)
fi

COMMIT_FILE=$1
COMMIT_MSG=$(cat $1)
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
JIRA_ID=$(echo "$CURRENT_BRANCH" | grep -Eo "[A-Z0-9]{1,10}-?[A-Z0-9]+-\d+")

if [ ! -z "$JIRA_ID" ]; then
    echo "$JIRA_ID $COMMIT_MSG" > $COMMIT_FILE
    echo "JIRA ID '$JIRA_ID', matched in current branch name, prepended to commit message. (Use --no-verify to skip)"
fi